version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Download Flutter SDK and generate Dart API docs
      - git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
      - cd flutter_app && $HOME/flutter/bin/flutter pub get
      - cd flutter_app && $HOME/flutter/bin/dart doc --output=../docs/docs/flutter-api

python:
  install:
    - method: pip
      path: ./crisscross_kit
    - requirements: ./docs/requirements.txt

mkdocs:
  configuration: ./docs/mkdocs.yml
