version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: ./crisscross_kit
    - requirements: ./crisscross_kit/docs/requirements.txt

mkdocs:
  configuration: ./crisscross_kit/docs/mkdocs.yml
