#!/usr/bin/env python3
'''
run_sequence_search.py

Purpose:
    This script performs the actual selection of an orthogonal set of DNA sequence pairs
    using the hybrid search algorithm. It selects sequences whose on-target
    energies fall within a desired range and prunes off-target interactions via
    iterative graph-based refinement.

    This script is intended to be run **after** initial exploration with
    `preanalyze_sequences.py` and optionally `analyze_on_target_range.py` to determine
    sensible energy cutoffs.

Main Steps:
    1. Set a fixed random seed for reproducibility.
    2. Generate the full pool of sequence pairs (with optional flanking sequences).
    3. Define energy cutoffs for on-target and off-target interactions based on prior analysis.
    4. Run the hybrid search algorithm to find a set of sequences with minimal cross-interaction.
    5. Save the selected sequences to file for downstream use.
    6. Recompute and visualize final on- and off-target energy distributions.

Usage:
    python run_sequence_search.py
'''

import random
from orthoseq_generator import helper_functions as hf
from orthoseq_generator import sequence_computations as sc
from orthoseq_generator.search_algorithm import hybrid_search





if __name__ == "__main__":
    # 1) Set a random seed for reproducibility 
    RANDOM_SEED = 42
    random.seed(RANDOM_SEED)

    # 2) Generate the full pool of 7-mer handle/antihandle pairs (no flanks here).
    ontarget8mer = sc.create_sequence_pairs_pool(
        length=7,
        fivep_ext="",
        threep_ext="",
        avoid_gggg=True
    )

    sequence_pairs_object = sc.SequencePairRegistry(
        length=7,
        fivep_ext="",
        threep_ext="",
        unwanted_substrings=[],
        apply_unwanted_to="core",
        seed=RANDOM_SEED
    )


    # 3) Define energy thresholds based on prior analysis
    hf.set_nupack_params(material='dna', celsius=37, sodium=0.05, magnesium=0.025)
    max_ontarget = -9.128
    min_ontarget = -10.38
    offtarget_limit = -7.2
    self_energy_limit = -2
    # 4) Run the hybrid search algorithm to find an orthogonal set of sequences
    # The subset size is the number of random sequences selected from the provided sequence pairs (ontarget8mer) each generation.
    # Higher subset sizes make the computation significantly slower. 
    # This function automatically save the sequences it found with an autogenerated name in the noflank_results folder.
    orthogonal_seq_pairs = hybrid_search(
        sequence_pairs_object,
        offtarget_limit,
        max_ontarget,
        min_ontarget,
        self_energy_limit,
        initial_fresh_pair_count=100,
        generations=5,
    )

    # 5) Save the selected orthogonal sequences to a file with a name you choose for later use
    hf.save_sequence_pairs_to_txt(orthogonal_seq_pairs, filename='ortho_10mers7.txt')

    # 6) Compute and plot the on-target and off-target energy distributions for the selected set
    onef, self_e_A, self_e_B = sc.compute_ontarget_energies(orthogonal_seq_pairs)
    offef = sc.compute_offtarget_energies(orthogonal_seq_pairs)

    stats = sc.plot_on_off_target_histograms(
        onef,
        offef,
        output_path='ortho_10mers.pdf'
    )

    self_stats = sc.plot_self_energy_histogram([self_e_A, self_e_B], bins=30, output_path='final_10mer_self_energies.pdf')
