# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hamming_evolve_communication.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'hamming_evolve_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"hamming_evolve_communication.proto\x12\nevoService\"\xd3\x01\n\rEvolveRequest\x12&\n\tslatArray\x18\x01 \x03(\x0b\x32\x13.evoService.Layer3D\x12(\n\x0bhandleArray\x18\x02 \x03(\x0b\x32\x13.evoService.Layer3D\x12=\n\nparameters\x18\x03 \x03(\x0b\x32).evoService.EvolveRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\".\n\x07Layer3D\x12#\n\x06layers\x18\x01 \x03(\x0b\x32\x13.evoService.Layer2D\",\n\x07Layer2D\x12!\n\x04rows\x18\x01 \x03(\x0b\x32\x13.evoService.Layer1D\"\x19\n\x07Layer1D\x12\x0e\n\x06values\x18\x01 \x03(\x05\"F\n\x0eProgressUpdate\x12\x0f\n\x07hamming\x18\x01 \x01(\x01\x12\x0f\n\x07physics\x18\x02 \x01(\x01\x12\x12\n\nisComplete\x18\x03 \x01(\x08\"\r\n\x0bStopRequest\"\x0e\n\x0cPauseRequest\"\x10\n\x0e\x45xportResponse\"#\n\rExportRequest\x12\x12\n\nfolderPath\x18\x01 \x01(\t\"9\n\rFinalResponse\x12(\n\x0bhandleArray\x18\x01 \x03(\x0b\x32\x13.evoService.Layer3D2\xab\x02\n\x0cHandleEvolve\x12\x46\n\x0b\x65volveQuery\x12\x19.evoService.EvolveRequest\x1a\x1a.evoService.ProgressUpdate0\x01\x12\x45\n\x0fPauseProcessing\x12\x18.evoService.PauseRequest\x1a\x18.evoService.PauseRequest\x12\x44\n\x0eStopProcessing\x12\x17.evoService.StopRequest\x1a\x19.evoService.FinalResponse\x12\x46\n\rrequestExport\x12\x19.evoService.ExportRequest\x1a\x1a.evoService.ExportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hamming_evolve_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVOLVEREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_EVOLVEREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_EVOLVEREQUEST']._serialized_start=51
  _globals['_EVOLVEREQUEST']._serialized_end=262
  _globals['_EVOLVEREQUEST_PARAMETERSENTRY']._serialized_start=213
  _globals['_EVOLVEREQUEST_PARAMETERSENTRY']._serialized_end=262
  _globals['_LAYER3D']._serialized_start=264
  _globals['_LAYER3D']._serialized_end=310
  _globals['_LAYER2D']._serialized_start=312
  _globals['_LAYER2D']._serialized_end=356
  _globals['_LAYER1D']._serialized_start=358
  _globals['_LAYER1D']._serialized_end=383
  _globals['_PROGRESSUPDATE']._serialized_start=385
  _globals['_PROGRESSUPDATE']._serialized_end=455
  _globals['_STOPREQUEST']._serialized_start=457
  _globals['_STOPREQUEST']._serialized_end=470
  _globals['_PAUSEREQUEST']._serialized_start=472
  _globals['_PAUSEREQUEST']._serialized_end=486
  _globals['_EXPORTRESPONSE']._serialized_start=488
  _globals['_EXPORTRESPONSE']._serialized_end=504
  _globals['_EXPORTREQUEST']._serialized_start=506
  _globals['_EXPORTREQUEST']._serialized_end=541
  _globals['_FINALRESPONSE']._serialized_start=543
  _globals['_FINALRESPONSE']._serialized_end=600
  _globals['_HANDLEEVOLVE']._serialized_start=603
  _globals['_HANDLEEVOLVE']._serialized_end=902
# @@protoc_insertion_point(module_scope)
