[compute]
enabled = true
lengths = [6]
range_sigmas = [1]
random_seed = 42
fivep_ext = "TTTT"
threep_ext = ""
avoid_gggg = false
use_library = false

[compare]
enabled = true
# If compute.enabled = false, provide existing PKL paths here
# pkl_paths = ["noflank_results/short_seq_5mer_sigma0p5_subset.pkl"]

# Leave empty to compute dynamically from max_on
# offtarget_limits = [-8.0, -7.5]

offtarget_step = 0.1
target_conflict_prob = 0.4
max_steps = 2000
random_seed = 41
num_runs = 5
num_vertices_to_remove = 0
max_iterations = 300
limit = 1e9
multistart = 1
population_size = 900
show_progress = false

[plot]
enabled = false

[output]
dir = "TTTT_results"
